# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Seokhyeon Jang
baseurl:        ""
url:            "https://boys-be-ambitious.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Seokhyeon Jang
  url:          https://boys-be-ambitious.github.io/
  email:        seokhyeonjang89@gmail.com  
  github:       boys-be-ambitious

# Custom vars
version:        3.4.2
github:
  repo:         https://github.com/boys-be-ambitious/boys-be-ambitious.github.io


disqus_shortname: 'seokhyeonjang'
# disqus_shortname: 'boys-be-ambitious'
disqus_url : 'http://disqus.com/by/disqus_hLIkSEMYCO'
disqus_id : 'disqus_hLIkSEMYCO'